server.port=${PORT:8080}
logging.level.org.atmosphere=warn

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true

# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.example,ca.xjyu

spring.security.oauth2.client.registration.auth0.client-id=IuWK3bBdZB99YLinKkAPXPs7EKPyvcsm
spring.security.oauth2.client.registration.auth0.client-secret=${AUTH0_CLIENT_SECRET}
spring.security.oauth2.client.registration.auth0.scope=openid,profile,email
spring.security.oauth2.client.provider.auth0.issuer-uri=https://dev-fowe3zegw2pnc83w.ca.auth0.com/
server.forward-headers-strategy=framework
spring.security.oauth2.client.registration.auth0.redirect-uri=http://localhost:8080/login/oauth2/code/auth0

spring.datasource.url=jdbc:mariadb://localhost:3306/prairieoprah
spring.datasource.username=dbuser
# REPLACE FOR PROD!!!!
spring.datasource.password=dbtestpwd
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect